# Generated by Django 4.2 on 2025-03-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_cliente_pedido_producto_sku_proveedor_comentarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad_entrega',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal_entrega',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AddField(
            model_name='cliente',
            name='comentarios',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_entrega',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='campo_libre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(null=True),
        ),
    ]
